# docker-compose.yml
version: '3.8'

services:
  spotify-db:
    image: citusdata/citus:latest
    container_name: spotify-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spotifyuser
      POSTGRES_PASSWORD: spotifypass
      POSTGRES_DB: spotifydb
    volumes:
      - spotify-data:/var/lib/postgresql/data
      - ./doker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spotifyuser -d spotifydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  spotify-data: